### ISSUE TITLE
Very impressive piece of work

### ISSUE THREAD

**Issue by adriatic** [dtaalbers/au-datatable#12]
The smallest possible contribution at this moment is this screenshot pointing out two typos:

![image](https://user-images.githubusercontent.com/2712405/31058733-6508dd90-a6c6-11e7-86f4-822540aded85.png)

(the second one points out that you need to remove the ' - as this is plural, not [saxon genitive](https://en.wikipedia.org/wiki/English_possessive) 😄

**Comment by dtaalbers** [comment]
Ha, knew I made some typo's. Thanks for the heads up. Will fix them as soon as possible!

**Comment by dtaalbers** [comment]
Thanks again!
